# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_stageBox(object):
    def setupUi(self, stageBox):
        stageBox.setObjectName("stageBox")
        stageBox.setWindowModality(QtCore.Qt.NonModal)
        stageBox.setEnabled(True)
        stageBox.resize(320, 130)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(stageBox.sizePolicy().hasHeightForWidth())
        stageBox.setSizePolicy(sizePolicy)
        stageBox.setSizeIncrement(QtCore.QSize(0, 0))
        stageBox.setStyleSheet("QWidget#stageBox {\n"
"    border-width:2px;\n"
"    border-color: rgb(66, 66, 66);\n"
"    border-style:ridge;\n"
"    padding:4px\n"
"}")
        self.gridLayoutWidget = QtWidgets.QWidget(stageBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 321, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 3, 1, 1)
        self.objectives_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.objectives_label.setObjectName("objectives_label")
        self.gridLayout.addWidget(self.objectives_label, 1, 0, 1, 1)
        self.objectivesFrame = QtWidgets.QFrame(self.gridLayoutWidget)
        self.objectivesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.objectivesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.objectivesFrame.setObjectName("objectivesFrame")
        self.gridLayout.addWidget(self.objectivesFrame, 2, 1, 1, 3)
        self.stage_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.stage_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stage_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stage_label.setLineWidth(1)
        self.stage_label.setMidLineWidth(0)
        self.stage_label.setTextFormat(QtCore.Qt.AutoText)
        self.stage_label.setProperty("stage", 0)
        self.stage_label.setObjectName("stage_label")
        self.gridLayout.addWidget(self.stage_label, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        self.newObjectiveButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.newObjectiveButton.setMinimumSize(QtCore.QSize(80, 0))
        self.newObjectiveButton.setAutoDefault(False)
        self.newObjectiveButton.setDefault(False)
        self.newObjectiveButton.setFlat(False)
        self.newObjectiveButton.setObjectName("newObjectiveButton")
        self.gridLayout.addWidget(self.newObjectiveButton, 3, 2, 1, 1)
        self.newStageButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.newStageButton.setFlat(False)
        self.newStageButton.setObjectName("newStageButton")
        self.gridLayout.addWidget(self.newStageButton, 4, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.moveUpButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.moveUpButton.setMinimumSize(QtCore.QSize(28, 28))
        self.moveUpButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/icons/16/arrow_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveUpButton.setIcon(icon)
        self.moveUpButton.setObjectName("moveUpButton")
        self.verticalLayout.addWidget(self.moveUpButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.deleteStageButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteStageButton.sizePolicy().hasHeightForWidth())
        self.deleteStageButton.setSizePolicy(sizePolicy)
        self.deleteStageButton.setMinimumSize(QtCore.QSize(28, 28))
        self.deleteStageButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("src/icons/16/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteStageButton.setIcon(icon1)
        self.deleteStageButton.setObjectName("deleteStageButton")
        self.verticalLayout.addWidget(self.deleteStageButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.moveDownButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.moveDownButton.setMinimumSize(QtCore.QSize(28, 28))
        self.moveDownButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("src/icons/16/arrow_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveDownButton.setIcon(icon2)
        self.moveDownButton.setObjectName("moveDownButton")
        self.verticalLayout.addWidget(self.moveDownButton)
        self.gridLayout.addLayout(self.verticalLayout, 0, 4, 5, 1)
        self.action_delete_stage = QtWidgets.QAction(stageBox)
        self.action_delete_stage.setIcon(icon1)
        self.action_delete_stage.setObjectName("action_delete_stage")

        self.retranslateUi(stageBox)
        QtCore.QMetaObject.connectSlotsByName(stageBox)

    def retranslateUi(self, stageBox):
        _translate = QtCore.QCoreApplication.translate
        stageBox.setWindowTitle(_translate("stageBox", "Form"))
        self.objectives_label.setText(_translate("stageBox", "objectives:"))
        self.stage_label.setText(_translate("stageBox", "stage %1"))
        self.newObjectiveButton.setText(_translate("stageBox", "New Objective"))
        self.newStageButton.setText(_translate("stageBox", "New Stage"))
        self.action_delete_stage.setText(_translate("stageBox", "delete_stage"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    stageBox = QtWidgets.QWidget()
    ui = Ui_stageBox()
    ui.setupUi(stageBox)
    stageBox.show()
    sys.exit(app.exec_())
